"""Markdown reports for the AI-Resistant Moat Scan -- a full ranked table
(moat-scan-report.md) and a fresh-high-scorers staging file
(moat-candidates-pending-review.md), the goat-heartbeat two-file pattern.

Both overwritten every run, advisor notes only. Copy style mirrors
cash_value_scan.render_report / _write_banner and
goat.heartbeat_scan.render_heartbeat_candidates_report.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

from . import config

_SYDNEY_TZ = ZoneInfo("Australia/Sydney")


def _today_sydney() -> str:
    return datetime.now(_SYDNEY_TZ).date().isoformat()


def _now_sydney_str() -> str:
    return datetime.now(_SYDNEY_TZ).strftime("%Y-%m-%d %H:%M %Z")


_DISCLAIMER = (
    "Auto-generated by the AI-resistant-moat daily scan -- overwritten every run. "
    "Advisor notes only; no trade action is ever suggested here (see SOUL.md). Run "
    "your own my-trader `find` / briefs-finance `assess` on anything you like."
)

_RUBRIC_CAVEAT = (
    "Rubric version {v} -- encodes a 2026 view of what AI can and cannot cheaply "
    "rebuild; revisit it periodically, do not treat it as permanent."
)

_TABLE_HEADER = (
    "| Ticker | Company | Industry | Moat | Quant | Qual | SoR | Switch | Ecosys "
    "| Regul | Breadth | Crit | Anti-signals | Worst rev YoY | Thesis | Tags |"
)
_TABLE_RULE = "|" + "---|" * 16

_BANNER_SUFFIX = "showing the last good run below."


def _clean(text: str) -> str:
    return (text or "").replace("|", "/").replace("\n", " ").strip()


def _fmt_score(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.1f}"


def _fmt_sub(sub_scores: dict[str, Any], key: str) -> str:
    v = sub_scores.get(key)
    return "-" if v is None else str(v)


def _fmt_pct(value: float | None) -> str:
    return "n/a" if value is None else f"{value:+.1f}%"


def _row_line(r: dict[str, Any]) -> str:
    sub = r.get("rubric_sub_scores") or {}
    moat = "n/a (no 10-K)" if r["moat_score"] is None else f"{r['moat_score']:.1f}"
    anti = "; ".join(r.get("anti_signals") or []) or "-"
    return "| " + " | ".join([
        r["ticker"],
        _clean(r.get("company", "")),
        _clean(r.get("industry", "")),
        moat,
        _fmt_score(r.get("quant_score")),
        _fmt_score(r.get("qualitative_score")),
        _fmt_sub(sub, "system_of_record"),
        _fmt_sub(sub, "switching_costs"),
        _fmt_sub(sub, "ecosystem_lockin"),
        _fmt_sub(sub, "regulatory_entrenchment"),
        _fmt_sub(sub, "workflow_breadth"),
        _fmt_sub(sub, "mission_criticality"),
        _clean(anti),
        _fmt_pct(r.get("worst_revenue_yoy")),
        _clean(r.get("thesis", "")),
        ", ".join(r.get("tags") or []) or "-",
    ]) + " |"


def render_report(result: dict[str, Any]) -> str:
    lines = [
        "# AI-Resistant Moat Scan",
        "",
        "What this is: US-listed companies ranked by how AI-durable their "
        "embedded-software moat is -- the Salesforce property, software engrained "
        "deeply enough in a customer's operations that the ROI of an AI replacement "
        "doesn't make sense. The score is a blended 0-100 number, half hard "
        "financials (margins, Rule of 40, revenue durability) and half an LLM read of "
        "a fixed 6-part rubric against the latest 10-K's Business + Risk Factors.",
        "",
        _RUBRIC_CAVEAT.format(v=config.RUBRIC_VERSION),
        "",
        _DISCLAIMER,
        "",
        f"**Last run: {_today_sydney()}** -- scanned {result['scanned']} ticker(s) "
        f"/ {result['screened_total']} screened total / slice "
        f"{result['slice_index'] + 1} of {result['slices']}.",
        "",
    ]

    rows = result.get("rows", [])
    if rows:
        lines += [_TABLE_HEADER, _TABLE_RULE]
        lines += [_row_line(r) for r in rows]
    else:
        lines.append("No companies scored this run.")

    lines += [
        "",
        "Sub-score columns (0-10): SoR = system of record, Switch = switching costs, "
        "Ecosys = ecosystem lock-in, Regul = regulatory entrenchment, Breadth = "
        "workflow breadth, Crit = mission criticality. Higher is a more AI-durable moat.",
        "Tag key: `held` / `watchlist` = already tracked in my-trader; `staged` = "
        "already in the pending-review file; `REVIEW:` = borderline ethical-filter flag "
        "(kept in the report, never staged).",
        "",
        f"Last auto-generated: {_now_sydney_str()}.",
    ]
    return "\n".join(lines) + "\n"


def render_candidates_report(result: dict[str, Any]) -> str:
    lines = [
        "# AI-Resistant Moat Candidates — Pending Review",
        "",
        "Auto-generated by the AI-resistant-moat daily scan -- a US-listed company "
        f"whose blended moat score is at or above {config.MOAT_STAGE_THRESHOLD:.0f} "
        "and that you don't already hold / watchlist. Review each one and either "
        "`promote-candidate` (writes it into my-trader's real watchlist, labeled "
        "AI-moat-approved) or `dismiss-candidate` (discards it). Edits here are "
        "overwritten on the next `scan` run.",
        "",
        _RUBRIC_CAVEAT.format(v=config.RUBRIC_VERSION),
        "",
        f"Scanned {result['scanned']} ticker(s), slice "
        f"{result['slice_index'] + 1}/{result['slices']}.",
        "",
        "| Ticker | Industry | Moat | Quant | Qual | Thesis | Flagged |",
        "|--------|----------|------|-------|------|--------|---------|",
    ]
    for row in result.get("pending_candidates", []):
        lines.append(
            f"| {row['ticker']} | {_clean(row.get('industry', ''))} "
            f"| {_fmt_score(row.get('moat_score'))} "
            f"| {_fmt_score(row.get('quant_score'))} "
            f"| {_fmt_score(row.get('qualitative_score'))} "
            f"| {_clean(row.get('thesis', ''))} | {str(row.get('flagged_at', ''))[:10]} |"
        )
    if not result.get("pending_candidates"):
        lines.append("| _(none)_ | | | | | | |")
    lines += ["", f"Last auto-generated: {_now_sydney_str()}."]
    return "\n".join(lines) + "\n"


def _write_banner(reason: str) -> None:
    """A run couldn't produce a trustworthy full report (Finviz screen failed and no
    cache) -> keep the previous report and prepend a single non-stacking banner."""
    path = config.MOAT_SCAN_REPORT_PATH
    banner = f"> {reason} ({_today_sydney()}) -- {_BANNER_SUFFIX}\n\n"
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        first_para, sep, rest = existing.partition("\n\n")
        if first_para.startswith("> ") and first_para.rstrip().endswith(_BANNER_SUFFIX):
            existing = rest if sep else ""
        path.write_text(banner + existing, encoding="utf-8")
    else:
        path.write_text(
            f"{banner}# AI-Resistant Moat Scan\n\nNo prior report to show.\n",
            encoding="utf-8",
        )


def write_report(result: dict[str, Any]) -> None:
    if result.get("finviz_failed") and not result.get("rows"):
        _write_banner("STALE -- Finviz screen fetch failed and no universe cache")
        return
    config.MOAT_SCAN_REPORT_PATH.write_text(render_report(result), encoding="utf-8")


def write_candidates_report(result: dict[str, Any]) -> None:
    config.MOAT_CANDIDATES_MD_PATH.write_text(
        render_candidates_report(result), encoding="utf-8"
    )
