"""Markdown report for the superinvestor fast-disclosure scanner -- overwritten every
run, advisor notes only. Copy style mirrors goat.insider_scan.render_insider_scan_report
('What this is:' opener, '## Run:' heading, Sydney-time footer)."""

from __future__ import annotations

from datetime import date, datetime
from typing import Any
from zoneinfo import ZoneInfo

from . import config

_SYDNEY_TZ = "Australia/Sydney"

# Reproduced verbatim from investments/superinvestor-filings-scanner-handoff.md so the
# alert is never oversold.
_HOW_TO_READ = (
    "For a passive concentrated filer like Pabrai the high-value events are "
    "**threshold crossings** (5%, 10%, exit) and **Form 4s on any name where they're "
    "already > 10%**. Ordinary position sizing inside 5-10% mostly still waits for the "
    "quarterly cycle -- set expectations accordingly so the alert isn't oversold. "
    "Deadlines: 13D = 5 business days after crossing 5%; 13G (passive) = 5 business "
    "days after crossing 5%; Form 4 = 2 business days for any trade once a > 10% "
    "owner; SEBI SAST Reg 29 = 2 working days for a 5% crossing or any >= 2% change "
    "past 5%."
)


def _now_sydney_str() -> str:
    return datetime.now(ZoneInfo(_SYDNEY_TZ)).strftime("%Y-%m-%d %H:%M %Z")


def _group_by_investor(alerts: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for a in alerts:
        grouped.setdefault(a.get("filer_display", a.get("filer_key", "Unknown")), []).append(a)
    return grouped


_RECENT_HEADER = [
    "| Source | Investor | Form | Issuer | % / Shares | Crossing | Filed |",
    "|--------|----------|------|--------|------------|----------|-------|",
]

_SOURCE_LABEL = {"edgar": "US EDGAR", "sast": "IN BSE SAST"}


def _recent_row(r: dict[str, Any]) -> str:
    pct = f"{r['pct_owned']:.1f}%" if r.get("pct_owned") is not None else ""
    shares = f"{r['shares']:,.0f}" if r.get("shares") is not None else ""
    size = " / ".join(x for x in (pct, shares) if x) or "-"
    src = _SOURCE_LABEL.get(r.get("source", ""), r.get("source", "") or "-")
    return (
        f"| {src} | {r.get('filer_display', '')} | {r.get('form_type', '')} "
        f"| {r.get('issuer', '')} | {size} | {r.get('material_crossing') or '-'} "
        f"| {r.get('filed_date') or '-'} |"
    )


def render_report(result: dict[str, Any]) -> str:
    new_filings = result.get("new_filings", [])
    recent = result.get("recent_filings", [])
    first_seed = result.get("first_seed", False)

    lines = [
        "# Superinvestor Fast-Disclosure Filings",
        "",
        "What this is: fast-disclosure filings by a tracked list of concentrated "
        "value investors -- US SEC 13D/G + Form 3/4/5, and India SEBI SAST "
        "Regulation 29 disclosures on BSE -- caught the day they appear instead of "
        "waiting up to ~135 days for the next 13F.",
        "",
        "Auto-generated by the superinvestor-filings daily scan -- overwritten every "
        "run. Advisor notes only; no trade action is ever suggested here (see SOUL.md). "
        "A US Form 4 by a > 10%-owner fund entity can also surface separately in Goat's "
        "insider scan from OpenInsider -- different table, different purpose, not "
        "cross-suppressed.",
        "",
        f"## Run: {date.today().isoformat()}",
        "",
    ]

    if first_seed:
        lines += [
            "First run for one or both legs: the seen-log was seeded silently with "
            "the last ~30 days of filings and no alert was sent for those. Alerts "
            "start from the next run.",
            "",
        ]

    lines += ["## New Since Last Run", ""]
    if new_filings:
        for investor, items in _group_by_investor(new_filings).items():
            lines.append(f"### {investor} -- {len(items)} new")
            for a in items:
                lines.append(f"- {a['summary']}")
                if a.get("raw_url"):
                    lines.append(f"  {a['raw_url']}")
            lines.append("")
    else:
        lines += ["No new fast-disclosure filings since the last run.", ""]

    lines += [
        f"## All Recent Filings (last {config.SUPERINVESTOR_LOOKBACK_DAYS} days)",
        "",
    ]
    if recent:
        lines += _RECENT_HEADER + [_recent_row(r) for r in recent]
    else:
        lines.append("No filings recorded yet.")
    lines += [""]

    lines += ["## How to read this", "", _HOW_TO_READ, ""]
    lines += [f"Last auto-generated: {_now_sydney_str()}."]
    return "\n".join(lines) + "\n"


def write_report(result: dict[str, Any]) -> None:
    config.SUPERINVESTOR_REPORT_PATH.write_text(render_report(result), encoding="utf-8")
