"""ETF-as-candidate heartbeat leg -- Part C of
.agent/plans/goat-industry-pipeline.md. Scans the full curated ETF universe
(config.GOAT_DMA_BREAKOUT_ETF_UNIVERSE, 57 tickers: 11 sector + 39 industry +
7 broad/commodity) UNCONDITIONALLY for the same heartbeat pattern every other
Goat heartbeat leg checks -- no rising-sector/industry prefilter, mirroring
dma_breakout_scan.fetch_universe_constituents's own ETF leg (no rising filter
there either -- an ETF has no GICS-sector membership of its own to gate on the
way a stock does). Per the orchestrator-independence pattern, this is its own
independent copy, not threaded from any other scan's output."""

from __future__ import annotations

import sqlite3
from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

from mytrader import db as mt_db, market_data

from . import config, db, dma_breakout_scan, fundamentals_context, heartbeat, price_history

_SYDNEY_TZ = ZoneInfo("Australia/Sydney")


def _today_sydney() -> str:
    """Module-private copy, not cross-imported -- per this codebase's convention."""
    return datetime.now(_SYDNEY_TZ).date().isoformat()


def run_etf_heartbeat_scan(conn: sqlite3.Connection) -> dict[str, Any]:
    scanned = 0
    new_candidates: list[dict[str, Any]] = []

    for ticker, label in config.GOAT_DMA_BREAKOUT_ETF_UNIVERSE.items():
        if ticker in config.GOAT_BANNED_TICKERS:
            continue
        try:
            frame = price_history.fetch_close_volume_history(ticker, config.GOAT_HEARTBEAT_HISTORY_LOOKBACK_DAYS)
            if frame is None:
                print(f"[goat-etf-heartbeat-scan] no price history for {ticker}, skipping")
                continue
            scanned += 1
            close = frame["Close"]
            volume = frame["Volume"]

            check = heartbeat.check_heartbeat_breakout(ticker, label, close, volume)
            if check.verdict != "interesting":
                continue

            if mt_db.get_holding_row(conn, ticker) is not None:
                continue
            if mt_db.get_watchlist_row(conn, ticker) is not None:
                continue
            if db.get_goat_pending_candidate(conn, ticker) is not None:
                continue

            data = market_data.fetch_ticker_data(ticker)
            if not dma_breakout_scan.passes_liquidity_floor("ETF", data):
                continue
            context = fundamentals_context.compute_survival_context(ticker, data)
            # Always False for an ETF (fundamentals_context short-circuits on
            # quoteType == "ETF") -- kept for shape-consistency with every other
            # Goat heartbeat leg, not because it can actually fire here.
            if context["insolvency_risk"]:
                continue

            exchange_name = data.info.get("fullExchangeName") or data.info.get("exchange")
            signal_detail = f"{check.detail}; survival context: {context['summary']}"
            db.insert_goat_pending_candidate(
                conn, ticker=ticker, sector_label=label,
                signal_detail=signal_detail, source="goat_etf_heartbeat_scan",
                company_name=None, exchange=exchange_name,
            )
            new_candidates.append({
                "ticker": ticker, "sector_label": label, "detail": signal_detail,
            })
        except Exception as e:
            print(f"[goat-etf-heartbeat-scan] error checking {ticker}: {e}")

    return {
        "scanned": scanned,
        "new_candidates": new_candidates,
        "pending_candidates": [
            dict(r) for r in db.get_all_goat_pending_candidates(conn)
            if r["source"] == "goat_etf_heartbeat_scan"
        ],
    }


def render_etf_heartbeat_candidates_report(result: dict[str, Any]) -> str:
    lines = [
        "# ETF Heartbeat Candidates — Pending Review",
        "",
        "Auto-generated by Goat's ETF heartbeat scan -- scans the full curated "
        "57-ticker ETF universe (11 sector + 39 industry + 7 broad/commodity) "
        "unconditionally for a tight, smooth sideways base, with fundamentals "
        "survival context attached (always N/A for a fund). No sector/industry "
        "rising-filter applies -- an ETF has no GICS-sector membership of its "
        "own to gate on. Review each one and either `promote-candidate` (writes "
        "it into my-trader's real watchlist, labeled Goat-approved) or "
        "`dismiss-candidate` (discards it). Edits here are overwritten on the "
        "next `scan-etf-heartbeat` run.",
        "",
        f"Scanned {result['scanned']} ticker(s) across the full ETF universe.",
        "",
        "| Ticker | Label | Signal | Flagged |",
        "|--------|-------|--------|---------|",
    ]
    for row in result["pending_candidates"]:
        lines.append(
            f"| {row['ticker']} | {row['sector_label']} | {row['signal_detail']} "
            f"| {row['flagged_at'][:10]} |"
        )
    lines += ["", f"Last auto-generated: {_today_sydney()}."]
    return "\n".join(lines) + "\n"


def write_etf_heartbeat_candidates_report(result: dict[str, Any]) -> None:
    config.GOAT_ETF_HEARTBEAT_CANDIDATES_MD_PATH.write_text(
        render_etf_heartbeat_candidates_report(result), encoding="utf-8"
    )
