"""Orchestrator for the S&P 500 heartbeat scan -- Goat Phase 3. Filters the
cached S&P 500 universe down to constituents of currently-rising sectors (per
Phase 2's own ranking), runs the heartbeat+breakout check per ticker, attaches
fundamentals survival context to any hit, and stages genuinely fresh candidates
into the existing goat_pending_candidates table (source="goat_heartbeat_scan").
Mirrors monitor.py's run_sector_scan/_stage_new_sector_candidates staging pattern
exactly."""

from __future__ import annotations

import sqlite3
from datetime import date
from typing import Any

from mytrader import db as mt_db
from mytrader import market_data

from . import config, db, fundamentals_context, heartbeat, price_history, sector_rotation, sp500_universe


def run_heartbeat_scan(conn: sqlite3.Connection) -> dict[str, Any]:
    closes = sector_rotation.fetch_all_sector_closes()
    ranking = sector_rotation.rank_sectors(closes)
    rising_etf_labels = {row["sector_label"] for row in ranking if row["rising"]}

    constituents = sp500_universe.get_or_refresh_sp500_constituents(conn)

    filtered = []
    for c in constituents:
        etf_label = config.GOAT_GICS_TO_ETF_SECTOR_LABEL.get(c["gics_sector"])
        if etf_label is None:
            print(f"[goat-heartbeat-scan] unmapped GICS sector {c['gics_sector']!r} for {c['ticker']}, skipping")
            continue
        if etf_label in rising_etf_labels:
            filtered.append(c)

    scanned = 0
    new_candidates: list[dict[str, Any]] = []
    for row in filtered:
        ticker = row["ticker"]
        sector_label = config.GOAT_GICS_TO_ETF_SECTOR_LABEL[row["gics_sector"]]
        try:
            close = price_history.fetch_close_history(ticker, config.GOAT_HEARTBEAT_HISTORY_LOOKBACK_DAYS)
            if close is None:
                print(f"[goat-heartbeat-scan] no price history for {ticker}, skipping")
                continue
            scanned += 1

            check = heartbeat.check_heartbeat_breakout(ticker, sector_label, close)
            if check.verdict != "interesting":
                continue

            data = market_data.fetch_ticker_data(ticker)
            context = fundamentals_context.compute_survival_context(ticker, data)
            if context["insolvency_risk"]:
                print(f"[goat-heartbeat-scan] {ticker} suppressed -- near-term insolvency risk")
                continue

            if mt_db.get_holding_row(conn, ticker) is not None:
                continue
            if mt_db.get_watchlist_row(conn, ticker) is not None:
                continue
            if db.get_goat_pending_candidate(conn, ticker) is not None:
                continue

            signal_detail = f"{check.detail}; survival context: {context['summary']}"
            db.insert_goat_pending_candidate(
                conn, ticker=ticker, sector_label=sector_label,
                signal_detail=signal_detail, source="goat_heartbeat_scan",
            )
            new_candidates.append({"ticker": ticker, "sector_label": sector_label, "detail": signal_detail})
        except Exception as e:
            print(f"[goat-heartbeat-scan] error checking {ticker}: {e}")

    return {
        "scanned": scanned,
        "rising_sectors": sorted(rising_etf_labels),
        "new_candidates": new_candidates,
        "pending_candidates": [
            dict(r) for r in db.get_all_goat_pending_candidates(conn) if r["source"] == "goat_heartbeat_scan"
        ],
    }


def render_heartbeat_candidates_report(result: dict[str, Any]) -> str:
    lines = [
        "# S&P 500 Heartbeat Candidates — Pending Review",
        "",
        "Auto-generated by Goat's weekly heartbeat scan -- a stock inside a currently "
        "rising sector (per sector-ranking.md) showing a sustained low-volatility "
        "consolidation followed by a fresh breakout above its 50-day MA (webinar Step "
        "1), with fundamentals survival context attached for you to judge yourself. "
        "Review each one and either `promote-candidate` (writes it into my-trader's "
        "real watchlist, labeled Goat-approved) or `dismiss-candidate` (discards it). "
        "Edits here are overwritten on the next `scan-heartbeat` run.",
        "",
        f"Scanned {result['scanned']} ticker(s) across "
        f"{len(result['rising_sectors'])} rising sector(s): "
        f"{', '.join(result['rising_sectors']) if result['rising_sectors'] else 'none'}.",
        "",
        "| Ticker | Sector | Signal | Flagged |",
        "|--------|--------|--------|---------|",
    ]
    for row in result["pending_candidates"]:
        lines.append(
            f"| {row['ticker']} | {row['sector_label']} | {row['signal_detail']} "
            f"| {row['flagged_at'][:10]} |"
        )
    lines += ["", f"Last auto-generated: {date.today().isoformat()}."]
    return "\n".join(lines) + "\n"


def write_heartbeat_candidates_report(result: dict[str, Any]) -> None:
    config.GOAT_HEARTBEAT_CANDIDATES_MD_PATH.write_text(
        render_heartbeat_candidates_report(result), encoding="utf-8"
    )
