"""Goat Monitor -- scheduled daily 150DMA exit-rule check against every my-trader
holding. Read-only against my-trader's holdings table; writes only to Goat's own
goat_alert_history table and goat-monitor-report.md. Never touches my-trader's
alert_history, monitor-report.md, holdings.md, or watchlist.md."""

from __future__ import annotations

import sqlite3
from datetime import date
from typing import Any

from mytrader import db as mt_db
from mytrader.checks import CheckResult

from . import config, db, exit_check, price_history

SEVERITY = "flag"
SOURCE_TABLE = "holdings"


def _reconcile_alerts(
    ticker: str, checks: list[CheckResult], conn: sqlite3.Connection
) -> list[dict[str, Any]]:
    new_alerts: list[dict[str, Any]] = []
    for check in checks:
        existing = db.get_open_goat_alert(conn, ticker, SOURCE_TABLE, check.name)
        if check.verdict == "flag":
            if existing is None:
                db.insert_goat_alert(
                    conn, ticker=ticker, source_table=SOURCE_TABLE,
                    check_name=check.name, severity=SEVERITY, message=check.detail,
                )
                new_alerts.append({
                    "ticker": ticker, "source_table": SOURCE_TABLE,
                    "check_name": check.name, "message": check.detail,
                })
        elif existing is not None:
            db.acknowledge_goat_alert(conn, existing["id"])
    return new_alerts


def run_monitor(conn: sqlite3.Connection) -> dict[str, Any]:
    holdings = mt_db.get_all_holdings(conn)

    new_alerts: list[dict[str, Any]] = []
    checked = 0
    for row in holdings:
        ticker = row["ticker"]
        try:
            close = price_history.fetch_close_history(ticker, config.GOAT_MA_HISTORY_LOOKBACK_DAYS)
            if close is None:
                print(f"[goat-monitor] no price history for {ticker}, skipping")
                continue
            check = exit_check.check_150dma_exit(ticker, close)
            new_alerts.extend(_reconcile_alerts(ticker, [check], conn))
            checked += 1
        except Exception as e:
            print(f"[goat-monitor] error checking {ticker}: {e}")

    return {
        "checked_holdings": checked,
        "new_alerts": new_alerts,
        "open_alerts": [dict(a) for a in db.get_open_goat_alerts(conn)],
    }


def render_report(result: dict[str, Any]) -> str:
    lines = [
        "# Goat Monitor Report",
        "",
        "Auto-generated by Goat Monitor -- overwritten every run. Advisor notes "
        "only; no trade action is ever suggested here (see SOUL.md).",
        "",
        f"## Run: {date.today().isoformat()}",
        f"Checked {result['checked_holdings']} holding(s) against the 150-day "
        "moving-average exit rule.",
        "",
        "### New Alerts This Run",
    ]
    if result["new_alerts"]:
        for a in result["new_alerts"]:
            lines.append(f"- **{a['ticker']}** -- {a['message']}")
    else:
        lines.append("No new material changes.")
    lines += ["", "### All Open Alerts"]
    if result["open_alerts"]:
        for a in result["open_alerts"]:
            lines.append(f"- **{a['ticker']}** -- {a['message']} (first flagged {a['created_at'][:10]})")
    else:
        lines.append("None.")
    lines += ["", f"Last auto-generated: {date.today().isoformat()}."]
    return "\n".join(lines) + "\n"


def write_report(result: dict[str, Any]) -> None:
    config.GOAT_MONITOR_REPORT_PATH.write_text(render_report(result), encoding="utf-8")


def maybe_notify(result: dict[str, Any]) -> None:
    if not result["new_alerts"]:
        return
    import sys
    from pathlib import Path

    _scripts_dir = Path(__file__).resolve().parent.parent.parent.parent / ".claude" / "scripts"
    sys.path.insert(0, str(_scripts_dir))
    from notifications import send_toast_notification

    n = len(result["new_alerts"])
    send_toast_notification(
        "Goat Monitor",
        f"{n} holding(s) below 150DMA exit threshold -- check investments/goat/monitor-report.md",
    )
