"""Goat Monitor -- scheduled daily 150DMA exit-rule check against every my-trader
holding. Read-only against my-trader's holdings table; writes only to Goat's own
goat_alert_history table and goat-monitor-report.md. Never touches my-trader's
alert_history, monitor-report.md, holdings.md, or watchlist.md."""

from __future__ import annotations

import sqlite3
from datetime import date
from typing import Any

from mytrader import db as mt_db
from mytrader.checks import CheckResult

from . import config, db, exit_check, price_history, sector_rotation

SEVERITY = "flag"
SOURCE_TABLE = "holdings"


# Public (not module-private) because goat/live_monitor.py also calls this
# directly -- shared dedup state (goat_alert_history) is riskier to duplicate
# than a pure computation would be, so this is imported properly rather than
# ported/copied the way price_history.py's crash_windows-derived logic was.
def reconcile_alerts(
    ticker: str, checks: list[CheckResult], conn: sqlite3.Connection
) -> list[dict[str, Any]]:
    new_alerts: list[dict[str, Any]] = []
    for check in checks:
        existing = db.get_open_goat_alert(conn, ticker, SOURCE_TABLE, check.name)
        if check.verdict == "flag":
            if existing is None:
                db.insert_goat_alert(
                    conn, ticker=ticker, source_table=SOURCE_TABLE,
                    check_name=check.name, severity=SEVERITY, message=check.detail,
                )
                new_alerts.append({
                    "ticker": ticker, "source_table": SOURCE_TABLE,
                    "check_name": check.name, "message": check.detail,
                })
        elif existing is not None:
            db.acknowledge_goat_alert(conn, existing["id"])
    return new_alerts


def run_monitor(conn: sqlite3.Connection) -> dict[str, Any]:
    holdings = mt_db.get_all_holdings(conn)

    new_alerts: list[dict[str, Any]] = []
    checked = 0
    for row in holdings:
        ticker = row["ticker"]
        try:
            close = price_history.fetch_close_history(ticker, config.GOAT_MA_HISTORY_LOOKBACK_DAYS)
            if close is None:
                print(f"[goat-monitor] no price history for {ticker}, skipping")
                continue
            check = exit_check.check_150dma_exit(ticker, close)
            new_alerts.extend(reconcile_alerts(ticker, [check], conn))
            checked += 1
        except Exception as e:
            print(f"[goat-monitor] error checking {ticker}: {e}")

    return {
        "checked_holdings": checked,
        "new_alerts": new_alerts,
        "open_alerts": [dict(a) for a in db.get_open_goat_alerts(conn)],
    }


def render_report(result: dict[str, Any]) -> str:
    lines = [
        "# Goat Monitor Report",
        "",
        "Auto-generated by Goat Monitor -- overwritten every run. Advisor notes "
        "only; no trade action is ever suggested here (see SOUL.md).",
        "",
        f"## Run: {date.today().isoformat()}",
        f"Checked {result['checked_holdings']} holding(s) against the 150-day "
        "moving-average exit rule.",
        "",
        "### New Alerts This Run",
    ]
    if result["new_alerts"]:
        for a in result["new_alerts"]:
            lines.append(f"- **{a['ticker']}** -- {a['message']}")
    else:
        lines.append("No new material changes.")
    lines += ["", "### All Open Alerts"]
    if result["open_alerts"]:
        for a in result["open_alerts"]:
            lines.append(f"- **{a['ticker']}** -- {a['message']} (first flagged {a['created_at'][:10]})")
    else:
        lines.append("None.")
    lines += [
        "",
        "### Sector Rotation",
        f"{len(result.get('new_sector_candidates', []))} new breakout candidate(s) this run. "
        "See sector-ranking.md and sector-candidates-pending-review.md.",
    ]
    lines += ["", f"Last auto-generated: {date.today().isoformat()}."]
    return "\n".join(lines) + "\n"


def write_report(result: dict[str, Any]) -> None:
    config.GOAT_MONITOR_REPORT_PATH.write_text(render_report(result), encoding="utf-8")


def maybe_notify(
    result: dict[str, Any], new_candidates: list[dict[str, Any]] | None = None,
    alert_label: str = "below 150DMA exit threshold",
) -> None:
    """new_candidates takes the actual staged-candidate dicts (ticker/sector_label/
    detail), not just a count -- 2026-08-17 fix: the previous int-only signature
    meant a WhatsApp alert could tell Shaun "1 new sector breakout candidate(s)"
    with no way to say which ticker/sector, forcing him to go check the report
    file for something the alert should have said outright."""
    candidates = new_candidates or []
    n_alerts = len(result["new_alerts"])
    if not n_alerts and not candidates:
        return
    import sys
    from pathlib import Path

    _scripts_dir = Path(__file__).resolve().parent.parent.parent.parent / ".claude" / "scripts"
    sys.path.insert(0, str(_scripts_dir))
    from notifications import send_toast_notification, send_whatsapp_notification

    parts = []
    if n_alerts:
        parts.append(f"{n_alerts} holding(s) {alert_label}")
    if candidates:
        parts.append(f"{len(candidates)} new sector breakout candidate(s)")
    summary = "; ".join(parts)

    # Toast only reaches whichever desktop happens to be running this (and is a
    # no-op fallback to console on the headless VPS) -- WhatsApp is the channel
    # that actually reaches Shaun's phone regardless of where monitor runs.
    send_toast_notification("Goat Monitor", summary + " -- check investments/goat/")

    lines = [f"Goat Monitor: {summary}."]
    if n_alerts:
        lines += [f"- {a['ticker']}: {a['message']}" for a in result["new_alerts"]]
    if candidates:
        lines += [f"- {c['ticker']} ({c['sector_label']}): {c['detail']}" for c in candidates]
    send_whatsapp_notification("\n".join(lines))


def _stage_new_sector_candidates(
    checks: list[tuple[str, str, CheckResult]], conn: sqlite3.Connection
) -> list[dict[str, Any]]:
    """checks: list of (ticker, sector_label, CheckResult). Mirrors
    candidate_sync.sync_new_candidates's three-way dedup (holding / watchlist /
    already-pending) before staging a new candidate -- prevents an
    already-promoted or still-active ETF from being re-staged every run while its
    breakout condition remains true."""
    new_candidates: list[dict[str, Any]] = []
    for ticker, sector_label, check in checks:
        if check.verdict != "interesting":
            continue
        if ticker in config.GOAT_BANNED_TICKERS:
            continue
        if mt_db.get_holding_row(conn, ticker) is not None:
            continue
        if mt_db.get_watchlist_row(conn, ticker) is not None:
            continue
        if db.get_goat_pending_candidate(conn, ticker) is not None:
            continue
        db.insert_goat_pending_candidate(
            conn, ticker=ticker, sector_label=sector_label, signal_detail=check.detail,
        )
        new_candidates.append({"ticker": ticker, "sector_label": sector_label, "detail": check.detail})
    return new_candidates


def run_sector_scan(conn: sqlite3.Connection) -> dict[str, Any]:
    closes = sector_rotation.fetch_all_sector_closes()
    ranking = sector_rotation.rank_sectors(closes)

    breakout_checks = []
    for ticker, sector_label in config.GOAT_SECTOR_ETFS.items():
        close = closes.get(ticker)
        if close is None:
            print(f"[goat-sector-scan] no price history for {ticker}, skipping breakout check")
            continue
        check = sector_rotation.check_sector_breakout(ticker, sector_label, close)
        breakout_checks.append((ticker, sector_label, check))

    new_candidates = _stage_new_sector_candidates(breakout_checks, conn)

    return {
        "ranking": ranking,
        "new_candidates": new_candidates,
        "pending_candidates": [dict(r) for r in db.get_all_goat_pending_candidates(conn)],
    }


def render_sector_ranking_report(result: dict[str, Any]) -> str:
    lines = [
        "# Goat Sector Rotation Ranking",
        "",
        "Auto-generated by Goat Monitor -- overwritten every run. Relative "
        f"performance over the trailing {config.GOAT_SECTOR_RANK_WINDOW_TRADING_DAYS} "
        "trading days across the 11 SPDR Select Sector ETFs. Advisor notes only; "
        "no trade action is ever suggested here (see SOUL.md).",
        "",
        "| Rank | Ticker | Sector | Return | Rising |",
        "|------|--------|--------|--------|--------|",
    ]
    for row in result["ranking"]:
        ret = f"{row['return_pct']:+.1f}%" if row["return_pct"] is not None else "—"
        rising = ("Yes" if row["rising"] else "No") if row["rising"] is not None else "—"
        lines.append(f"| {row['rank']} | {row['ticker']} | {row['sector_label']} | {ret} | {rising} |")
    lines += ["", f"Last auto-generated: {date.today().isoformat()}."]
    return "\n".join(lines) + "\n"


def write_sector_ranking_report(result: dict[str, Any]) -> None:
    config.GOAT_SECTOR_RANKING_MD_PATH.write_text(
        render_sector_ranking_report(result), encoding="utf-8"
    )


def render_sector_candidates_report(result: dict[str, Any]) -> str:
    lines = [
        "# Sector Breakout Candidates — Pending Review",
        "",
        "Auto-generated by Goat Monitor -- a fresh 50DMA-cross-and-rising breakout "
        "on a sector ETF (webinar Step 1). Review each one and either "
        "`promote-candidate` (writes it into my-trader's real watchlist, labeled "
        "Goat-approved) or `dismiss-candidate` (discards it). Edits here are "
        "overwritten on the next `monitor`/`scan-sectors` run.",
        "",
        "| Ticker | Sector | Signal | Flagged |",
        "|--------|--------|--------|---------|",
    ]
    for row in result["pending_candidates"]:
        lines.append(
            f"| {row['ticker']} | {row['sector_label']} | {row['signal_detail']} "
            f"| {row['flagged_at'][:10]} |"
        )
    lines += ["", f"Last auto-generated: {date.today().isoformat()}."]
    return "\n".join(lines) + "\n"


def write_sector_candidates_report(result: dict[str, Any]) -> None:
    config.GOAT_SECTOR_CANDIDATES_MD_PATH.write_text(
        render_sector_candidates_report(result), encoding="utf-8"
    )
